SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES  +=$(PWD) ../xor_rtl/dut.v
#VERILOG_SOURCES  +=$(PWD) ../wrapper/waves.v
MODULE = xor_test
TOPLEVEL = dut
include $(shell cocotb-config --makefiles)/Makefile.sim